const $=s=>document.querySelector(s);
const SITE_PASSWORD='123ooo#@!OOO',PASSWORD_KEY='isaiahs-mlv:site-access:v1';
const gate=$('#password-gate'),shell=$('#site-shell');
function unlock(){gate.hidden=true;gate.style.display='none';gate.setAttribute('aria-hidden','true');shell.hidden=false;shell.style.display='block';}
try{if(sessionStorage.getItem(PASSWORD_KEY)==='ok')unlock();}catch{}
$('#password-form').addEventListener('submit',event=>{event.preventDefault();const input=$('#site-password');const valid=input.value===SITE_PASSWORD;if(valid){try{sessionStorage.setItem(PASSWORD_KEY,'ok');}catch{}unlock();input.value='';}else{$('#password-error').hidden=false;input.select();}});
let sections=[],byName=new Map(),active='MLV Title Screen';
const groups={Games:{raw:'ġɑᗰΣʂ',art:true,choices:[['Sites','site-group'],['Singular games','singular'],['Extra.','direct'],['Google Doodles','direct'],['HTML','direct'],['Scratch','direct']]},Proxies:{raw:'РRo𝑥ɪΣʂ',art:true,choices:[['Sites','proxy-group'],['Extra','proxy-extra']]},TV:{raw:'┬ѵ',choices:[['┬ѵ.','direct']]},Music:{raw:'ɱυʂí¢',choices:[['1','direct'],['2','direct']]},Random:{raw:'Random',choices:[['Google Drive','direct'],['My Personal Favorites','direct']]},'Tools/Al':{raw:'Tools/Al',art:true,choices:[['1.','direct'],['2.','direct'],['3.','direct'],['4.','direct']]},Documents:{raw:'Documents',choices:[['Games','direct'],['My List','direct']]}};
const singular=['MINECRAFT','FNAF','BASKETBALL STARS','CHESS.COM','SLOPE','Random,'];
const proxy=['INTERSTEALLER','DOGE.','DOGE CENSOR','ASTROID','SHADOW','NETTLE WEB','SUNSET','ARSENIC','UTOPIA','FROGGIES ARCADE V3','ACCELERATION','EMERALD','ART CLASS','1346.lol','ACCELERATE','BOREDOM','BREAKIUM','CAMOUFALGE','CANLITE','CROXY PROXY','EQUINOX','FERN','ARCTIC','CHERRI','OPIUM','PHOTON','STUDY HUB','SERUM OS','DAYDREAMX','VOID NETWORK','BULL-33'];
const sites=['DIESMOS','NOCTURUNE','PETEZAH','MIST','GN MATH','UGS FILE','DUCK MATH','KAMAT','SEA BEANS','NIKE HUB','MELONSODA','SAKURA',"SYCE'S GAME SHACK",'WEBLFG/UBG100',"Isaiah's MLV"];
const imported={Games:[],Proxies:[],GameSites:[],TV:[],Music:[],Documents:[]};
const withImported=(base,category)=>[...base,...(imported[category]||[])];
function section(name){
 const items=byName.get(name)||[];
 if(!items.length)return {name,body:'',links:[],images:[],imageLinks:[]};
 const links=[...new Set(items.flatMap(x=>x.links||[]).filter(Boolean))];
 const imageLinks=[...new Set(items.flatMap(x=>x.imageLinks||[]).filter(Boolean))];
 const images=[...new Set(items.flatMap(x=>Array.isArray(x.images)?x.images:(x.image?[x.image]:[])).filter(Boolean))];
 const body=items.map(x=>x.body||'').filter(Boolean).join('\n\n');
 const textLinks=[...body.matchAll(/(?:https?|mailto):[^\s<>{}\"']+/gi)].map(m=>m[0].replace(/[.,;:!?)]}+$/,''));
 const bareLinks=[...body.matchAll(/\b(?:storage\.googleapis\.com|s3\.[a-z0-9.-]+|[a-z0-9.-]+\.vercel\.app)(?:\/[^\s<>{}\"']*)?/gi)].map(m=>m[0].replace(/[.,;:!?)]}+$/,'')).map(u=>/^https?:/i.test(u)?u:'https://'+u);
 return {name,body,links:[...new Set([...links,...textLinks,...bareLinks])],imageLinks,images};
}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function linksFor(s,mode){let a=[...(s.links||[]),...(s.imageLinks||[])];if(mode==='unblocked')a=a.filter(u=>/^(?:https?:\/\/)?(?:s3\.|storage\.googleapis\.com|[^/]+\.vercel\.app)(\/|$)/i.test(u));if(mode==='vault')a=a.filter(u=>/^https?:\/\/raw\.githubusercontent\.com/i.test(u));return [...new Set(a)]}
function grid(s,mode='unchecked'){let a=linksFor(s,mode);if(!a.length)return '<p class="note">No links were found for this section in the document.</p>';return '<div class="links">'+a.map(u=>`<a class="link" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(u)}</a>`).join('')+'</div>'}
function imageMarkup(s,name){let targets=[...(s.imageLinks||[]),...(s.links||[])].filter(Boolean).filter((u,i,a)=>a.indexOf(u)===i);return (s.images||[]).map(src=>{let links=targets.map(u=>`<a class="document-image-link" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(u)}</a>`).join('');return `<figure class="document-image-wrap"><a class="document-image-target" href="${esc(targets[0]||'#')}" target="_blank" rel="noopener noreferrer"><img class="document-image" src="${esc(src)}" alt="Embedded image from ${esc(name)}"></a>${links?`<figcaption class="document-image-links">${links}</figcaption>`:''}</figure>`}).join('')}
function modes(name){let s=section(name);let image=imageMarkup(s,name);return `<div class="section-head"><div><h1>${esc(name)}</h1><p>${linksFor(s).length} links copied from the document</p></div></div>${image}<div class="filters"><button class="filter active" data-mode="unchecked">Unchecked</button><button class="filter" data-mode="vault">Link Vault</button><button class="filter" data-mode="unblocked">Unblocked</button></div><div id="filtered">${grid(s)}</div><details><summary>Text from this tab</summary><pre class="ascii">${esc(s.body)}</pre></details>`}
function group(label){let g=groups[label],s=section(g.raw),choices=[...g.choices];if(label==='TV')choices.push(...withImported([], 'TV').map(n=>[n,'direct']));if(label==='Music')choices.push(...withImported([], 'Music').map(n=>[n,'direct']));return `<div class="section-head"><div><h1>${label}</h1><p>Choose a section to continue.</p></div></div>${g.art?`<pre class="ascii">${esc(s.body.split('\n\n')[0])}</pre>`:''}<div class="choices">${choices.map(([t,a])=>`<button class="choice" data-action="${a}" data-name="${t}">${t}</button>`).join('')}</div>`}
function list(title,names,action){return `<div class="section-head"><div><h1>${title}</h1><p>Select a name, then choose a link view.</p></div></div><div class="subtabs">${names.map(n=>`<button class="subtab" data-action="${action}" data-name="${n}">${n}</button>`).join('')}</div>`}
function render(){let v=$('#view');if(active==='MLV Title Screen'||active==='Information/Credits'){v.innerHTML=`<div class="section-head"><h1>${active}</h1></div><pre class="ascii">${esc(section(active).body)}</pre>`;return}if(groups[active]){v.innerHTML=group(active);return}if(active.startsWith('mode|')){v.innerHTML=modes(active.split('|')[1]);return}v.innerHTML=modes(active)}
function openSection(name){active='mode|'+name;location.hash=encodeURIComponent(active);render()}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let a=b.dataset.action,n=b.dataset.name;if(b.classList.contains('filter')){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');let name=decodeURIComponent(location.hash.slice(1)).split('|')[1];$('#filtered').innerHTML=grid(section(name),b.dataset.mode);return}if(a==='site-group')$('#view').innerHTML=list('Sites',[...withImported(sites,'Proxies'),...withImported([], 'GameSites')],'select');else if(a==='singular')$('#view').innerHTML=list('Singular games',withImported(singular,'Games'),'select');else if(a==='proxy-group')$('#view').innerHTML=list('Proxy sites',withImported(proxy,'Proxies'),'select');else if(a==='proxy-extra')$('#view').innerHTML=list('Proxy extras',['A Few Million','Random.'],'select');else if(a==='select'||a==='direct')openSection(n);else if(b.closest('#topnav')){active=n;location.hash=encodeURIComponent(n);render()}});
function nav(){let n=$('#topnav');['Games','Proxies','TV','Music','Random','Tools/Al','Documents','MLV Title Screen','Information/Credits'].forEach(x=>{let b=document.createElement('button');b.textContent=x;b.dataset.name=x;n.append(b)})}
fetch('content.json').then(r=>r.json()).then(data=>{for(const s of data){if(!byName.has(s.name))byName.set(s.name,[]);byName.get(s.name).push(s);if(s.category){const cats=Array.isArray(s.category)?s.category:[s.category];for(const c of cats)if(imported[c]&&!imported[c].includes(s.name))imported[c].push(s.name)}};$('#hero-art').textContent=section('MLV Title Screen').body.slice(0,1600);nav();let h=decodeURIComponent(location.hash.slice(1));if(h)active=h;render()}).catch(()=>{$('#view').innerHTML='<p class="note">The document export could not be loaded.</p>';nav()});
